### ISSUE TITLE
Add sonarlint

### ISSUE THREAD

**Issue by chrisemke** [aHub-Tech/hub-site-backend#1]
Add sonarlint like we did in the "live divulgador" project, I don't have enough permissions to do that 

@aHub-Tech/devops

**Comment by vcwild** [comment]
@chrisemke  please, tell the **specific steps** of what we would need to do (prints may help). As of right now, I am not the only member of @aHub-Tech/devops and we are trying to bring the teams in sync and improve our workflow.

In the near future this will be the new standard for every member of @aHub-Tech/projects

**Comment by chrisemke** [comment]
I made the tutorial to make it easier for you to apply sonarlint

https://sonarcloud.io/

![image](https://user-images.githubusercontent.com/63082743/152782939-cadd593c-4580-41b6-aff0-29ce665b85d4.png)

![image](https://user-images.githubusercontent.com/63082743/152783048-6b8b5e34-f7e3-43b0-b618-d3a30cd46016.png)

![image](https://user-images.githubusercontent.com/63082743/152783103-e540ddd6-93c1-4753-9aae-d771d016ee9d.png)

![image](https://user-images.githubusercontent.com/63082743/152783153-36de1faa-f843-43a8-adcb-2355e1be6fa3.png)

**Comment by vcwild** [comment]
Adicionado!
